# Generated by Django 4.2.7 on 2025-12-03 12:09

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAlga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('factor_conversion', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Factor para cálculos de conversión', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Factor de Conversión')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Tipo de Alga',
                'verbose_name_plural': 'Tipos de Algas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45, unique=True, verbose_name='Nombre de Usuario')),
                ('password', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('email', models.EmailField(max_length=45, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Trabajador', 'Trabajador'), ('Socio', 'Socio')], max_length=45, verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(help_text='Nombre del cliente internacional', max_length=200, verbose_name='Nombre de la Empresa')),
                ('pais', models.CharField(help_text='País del cliente', max_length=100, verbose_name='País')),
                ('contacto', models.CharField(blank=True, max_length=200, null=True, verbose_name='Persona de Contacto')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de Contacto')),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramos (kg)'), ('ton', 'Toneladas (ton)'), ('lb', 'Libras (lb)')], default='kg', max_length=10, verbose_name='Unidad de Medida Preferida')),
                ('formato_preferido', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('ambos', 'PDF y Excel')], default='pdf', max_length=10, verbose_name='Formato de Reporte Preferido')),
                ('mostrar_capacidad_instalada', models.BooleanField(default=True, help_text='Incluir información de capacidad productiva', verbose_name='Mostrar Capacidad Instalada')),
                ('mostrar_disponibilidad', models.BooleanField(default=True, help_text='Incluir información de disponibilidad mensual', verbose_name='Mostrar Disponibilidad')),
                ('mostrar_historial_produccion', models.BooleanField(default=True, help_text='Incluir historial de producción reciente', verbose_name='Mostrar Historial de Producción')),
                ('periodo_historial_meses', models.IntegerField(default=6, help_text='Número de meses de historial a incluir', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Período de Historial (meses)')),
                ('activo', models.BooleanField(default=True, verbose_name='Configuración Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Configuración de Reporte',
                'verbose_name_plural': 'Configuraciones de Reportes',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['empresa'], name='gestion_alg_empresa_1fdab2_idx'), models.Index(fields=['activo'], name='gestion_alg_activo_40c11f_idx')],
            },
        ),
        migrations.CreateModel(
            name='CapacidadProductiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(help_text='Primer día del mes para el registro de capacidad', verbose_name='Mes')),
                ('capacidad_mensual_maxima', models.DecimalField(decimal_places=2, help_text='Capacidad máxima de producción mensual en kilogramos', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Capacidad Mensual Máxima (kg)')),
                ('capacidad_anual_maxima', models.DecimalField(decimal_places=2, help_text='Capacidad máxima de producción anual en kilogramos', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Capacidad Anual Máxima (kg)')),
                ('volumen_producido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Volumen producido en el mes', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Volumen Producido (kg)')),
                ('volumen_comprometido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Volumen ya comprometido con clientes', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Volumen Comprometido (kg)')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Capacidad Productiva',
                'verbose_name_plural': 'Capacidades Productivas',
                'ordering': ['-mes'],
                'indexes': [models.Index(fields=['-mes'], name='gestion_alg_mes_31a5f4_idx')],
                'unique_together': {('mes',)},
            },
        ),
        migrations.CreateModel(
            name='RegistroProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_cosechada', models.DecimalField(decimal_places=2, help_text='Cantidad en kilogramos', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad Cosechada (kg)')),
                ('sector', models.CharField(max_length=100, verbose_name='Sector de Cosecha')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('tipo_alga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='gestion_algas.tipoalga', verbose_name='Tipo de Alga')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_produccion', to='gestion_algas.usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Producción',
                'verbose_name_plural': 'Registros de Producción',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['-fecha_registro'], name='gestion_alg_fecha_r_a21518_idx'), models.Index(fields=['usuario', '-fecha_registro'], name='gestion_alg_usuario_48dd8b_idx'), models.Index(fields=['tipo_alga', '-fecha_registro'], name='gestion_alg_tipo_al_030625_idx')],
            },
        ),
        migrations.CreateModel(
            name='ControlAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_origen', models.GenericIPAddressField(verbose_name='IP de Origen')),
                ('tipo_acceso', models.CharField(choices=[('login_exitoso', 'Login Exitoso'), ('login_fallido', 'Login Fallido'), ('logout', 'Logout'), ('acceso_denegado', 'Acceso Denegado')], max_length=50, verbose_name='Tipo de Acceso')),
                ('fecha_acceso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Acceso')),
                ('detalles', models.TextField(blank=True, null=True, verbose_name='Detalles')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos', to='gestion_algas.usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Control de Acceso',
                'verbose_name_plural': 'Control de Accesos',
                'ordering': ['-fecha_acceso'],
                'indexes': [models.Index(fields=['-fecha_acceso'], name='gestion_alg_fecha_a_65a48f_idx'), models.Index(fields=['usuario', '-fecha_acceso'], name='gestion_alg_usuario_63329e_idx')],
            },
        ),
    ]
