# Generated by Django 4.2.7 on 2025-12-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_algas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionreporte',
            name='fecha_desde',
            field=models.DateField(blank=True, help_text='Fecha inicial del reporte personalizado', null=True, verbose_name='Fecha Desde'),
        ),
        migrations.AddField(
            model_name='configuracionreporte',
            name='fecha_hasta',
            field=models.DateField(blank=True, help_text='Fecha final del reporte personalizado', null=True, verbose_name='Fecha Hasta'),
        ),
        migrations.AddField(
            model_name='configuracionreporte',
            name='incluir_observaciones',
            field=models.BooleanField(default=False, help_text='Mostrar observaciones de cada registro', verbose_name='Incluir Observaciones'),
        ),
        migrations.AddField(
            model_name='configuracionreporte',
            name='mostrar_graficos',
            field=models.BooleanField(default=True, help_text='Incluir gráficos de tendencias y comparativas', verbose_name='Mostrar Gráficos'),
        ),
        migrations.AddField(
            model_name='configuracionreporte',
            name='sectores_especificos',
            field=models.CharField(blank=True, help_text='Sectores separados por comas (vacío = todos)', max_length=500, null=True, verbose_name='Sectores Específicos'),
        ),
        migrations.AddField(
            model_name='configuracionreporte',
            name='tipos_alga',
            field=models.ManyToManyField(blank=True, help_text='Selecciona tipos específicos (vacío = todos)', to='gestion_algas.tipoalga', verbose_name='Tipos de Alga'),
        ),
        migrations.AddField(
            model_name='configuracionreporte',
            name='usar_fecha_personalizada',
            field=models.BooleanField(default=False, help_text='Si está activo, ignora el período de historial', verbose_name='Usar Rango de Fecha Personalizado'),
        ),
    ]
