# Generated by Django 4.2.7 on 2025-12-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_algas', '0002_configuracionreporte_fecha_desde_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Trabajador', 'Trabajador')], max_length=45, verbose_name='Rol'),
        ),
    ]
