# Generated by Django on 2025-11-26

from django.db import migrations


def modificar_usuario(apps, schema_editor):
    """
    Modificar la tabla de usuarios agregando el campo telefono
    """
    with schema_editor.connection.cursor() as cursor:
        # Verificar si la columna ya existe
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'gestion_algas_usuario' 
            AND COLUMN_NAME = 'telefono'
        """)
        
        existe = cursor.fetchone()[0]
        
        # Agregar campo telefono solo si no existe
        if not existe:
            cursor.execute("""
                ALTER TABLE gestion_algas_usuario 
                ADD COLUMN telefono VARCHAR(15) NOT NULL DEFAULT '0000000000'
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_algas', '0003_alter_usuario_rol'),
    ]

    operations = [
        migrations.RunPython(modificar_usuario, reverse_code=migrations.RunPython.noop),
    ]
