# Generated by Django 4.2.7 on 2025-12-16 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_algas', '0003_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroproduccion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_produccion', to='gestion_algas.usuario', verbose_name='Usuario'),
        ),
    ]
