# Generated by Django 4.2.7 on 2025-12-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_algas', '0004_alter_registroproduccion_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroproduccion',
            name='nombre_usuario',
            field=models.CharField(default='Usuario eliminado', help_text='Nombre del usuario que realizó el registro', max_length=100, verbose_name='Nombre del Usuario'),
            preserve_default=False,
        ),
    ]
