# Generated by Django 4.2.7 on 2025-12-16 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_algas', '0005_registroproduccion_nombre_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capacidadproductiva',
            name='volumen_producido',
        ),
    ]
