# Generated by Django 4.2.7 on 2025-12-16 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_algas', '0006_remove_capacidadproductiva_volumen_producido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capacidadproductiva',
            name='capacidad_anual_maxima',
        ),
        migrations.RemoveField(
            model_name='capacidadproductiva',
            name='volumen_comprometido',
        ),
    ]
