# Generated by Django 4.2.7 on 2025-12-16 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_algas', '0007_remove_capacidadproductiva_capacidad_anual_maxima_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroproduccion',
            name='nombre_tipo_alga',
            field=models.CharField(default='', help_text='Nombre del tipo de alga (preservado incluso si el tipo es eliminado)', max_length=100, verbose_name='Nombre del Tipo de Alga'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registroproduccion',
            name='tipo_alga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='gestion_algas.tipoalga', verbose_name='Tipo de Alga'),
        ),
    ]
